### ISSUE TITLE
Set comparison test: "dead code"

### ISSUE THREAD

**Issue by tp** [concordancejs/concordance#19]
I wanted to check out your `Set` comparison tests and found the following lines of code:

https://github.com/concordancejs/concordance/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/test/compare.js#L32:L36

As far as I can tell, modifying `a1` and `a2` there has no effect and should probably be removed (or changed to `a3` and `a4` if you want to test the ordering (or split into two different tests).

**Comment by novemberborn** [comment]
Yea that seems unnecessary, nice find! The comparison will yield `false` because the sets themselves are unequal.
