### ISSUE TITLE
Serialized function name descriptors must take engine support into account

### ISSUE THREAD

**Issue by novemberborn** [concordancejs/concordance#20]
Older V8 versions don't generate a function name in all circumstances, see https://kangax.github.io/compat-table/es6/#function_name_property.

Determine which scenarios are supported and store this in the serialization. Then, when comparing a deserialized function descriptor assess the current engine support to decide whether a name mismatch is an error or can be ignored.

**Comment by sindresorhus** [comment]
More focused: http://node.green/#ES2015-built-in-extensions-function--name--property

**Comment by novemberborn** [comment]
> Determine which scenarios are supported and store this in the serialization.

See https://github.com/novemberborn/function-name-support.

There is one failure case when Istanbul is used: https://github.com/istanbuljs/istanbuljs/issues/59. If we can fix this then we'll be able to include function names in serializations and correctly asses whether a mismatch is an error.
