### ISSUE TITLE
RangeError: 'offset' is out of bounds when comparing empty (length 0) Buffers

### ISSUE THREAD

**Issue by atesgoral** [concordancejs/concordance#37]
Test case:

```
const c = require('concordance');

const a = Buffer.from([]);
const b = Buffer.from([]);

console.log(c.compare(a, b));
```

Output:

> RangeError: 'offset' is out of bounds
>     at RangeError (native)
>     at fromArrayBuffer (buffer.js:257:20)
>     at Function.Buffer.from (buffer.js:128:12)
>     at getBuffer (lib/complexValues/typedArray.js:15:25)
>     at describe (lib/complexValues/typedArray.js:24:13)
>     at describeComplex (lib/describe.js:119:22)
>     at c (lib/describe.js:141:12)
>     at describe (lib/describe.js:168:10)
>     at Object.compare (lib/compare.js:98:12)

Version is 3.0.0

**Comment by novemberborn** [comment]
Hi @atesgoral. Which Node.js version are you using?

**Comment by atesgoral** [comment]
@novemberborn v6.0.0

**Comment by atesgoral** [comment]
Just tested with 6.11.3 and the problem does not exist. So, maybe this is a non-issue.

**Comment by novemberborn** [comment]
Interesting. It does look like a Node.js issue, yes.
